import { ActionRowBuilder, ButtonBuilder, ButtonStyle, EmbedBuilder } from 'discord.js';
import { recordGame } from './store.js';

export const activeGames = new Map();
const timers = new Map();
const SERVER = new Set(['xo','mafia','chairs','rps','dice','hotxo','hide','replica','country','draw','word']);
const names = {xo:'XO',mafia:'مافيا',chairs:'كراسي',rps:'حجرة ورقة مقص',dice:'نرد',hotxo:'HotXO',hide:'غميضة',replica:'ريبلكا',country:'خمّن الدولة',draw:'خمّن الرسمة',word:'خمّن الكلمة'};
const rnd=a=>a[Math.floor(Math.random()*a.length)];
const shuffle=a=>[...a].sort(()=>Math.random()-.5);
const sleep=ms=>new Promise(r=>setTimeout(r,ms));
const mention=a=>a.map(x=>`• <@${x}>`).join('\n');
const lobbyRow=id=>new ActionRowBuilder().addComponents(
 new ButtonBuilder().setCustomId(`lobby:${id}:join`).setLabel('انضمام').setStyle(ButtonStyle.Primary),
 new ButtonBuilder().setCustomId(`lobby:${id}:start`).setLabel('بدء').setStyle(ButtonStyle.Success),
 new ButtonBuilder().setCustomId(`lobby:${id}:cancel`).setLabel('إلغاء').setStyle(ButtonStyle.Danger));

export async function handleGameCommand(i,id){
 if(!SERVER.has(id)&&!['button','fast','split','merge','flag','reverse','letter','correct','sort','colors','emoji','reveal'].includes(id)) return i.reply({content:'هذه اللعبة غير متاحة.',ephemeral:true});
 if(SERVER.has(id)) return lobby(i,id); return mini(i,id);
}
async function lobby(i,id){
 if(activeGames.has(i.channelId)) return i.reply({content:'توجد لعبة نشطة في هذه القناة.',ephemeral:true});
 const s={id,channelId:i.channelId,guildId:i.guildId,players:[],started:false,cancelled:false}; activeGames.set(i.channelId,s);
 await i.reply({embeds:[embedLobby(id,[])],components:[lobbyRow(id)]}); s.message=await i.fetchReply(); timers.set(i.channelId,setTimeout(()=>autoStart(s),30000));
}
const embedLobby=(id,p)=>new EmbedBuilder().setTitle(`🎮 ${names[id]}`).setDescription(`ينضم اللاعبون بالضغط على **انضمام**.\n\n**اللاعبون (${p.length}/20):**\n${p.length?mention(p):'لا يوجد لاعبون بعد.'}`);
async function autoStart(s){if(!activeGames.has(s.channelId)||s.started||s.players.length<2)return; s.started=true;const c=s.message.channel;await s.message.edit({components:[lobbyRow(s.id)]});await runServer(c,s);}
async function end(s,c,w=[]){if(s.done)return;s.done=true;activeGames.delete(s.channelId);clearTimeout(timers.get(s.channelId));const text=w.length?w.map(x=>`<@${x}>`).join('، '):'لا يوجد فائز.';await c.send({embeds:[new EmbedBuilder().setTitle(`🏆 انتهت ${names[s.id]}`).setDescription(`الفائز: ${text}`)]}).catch(()=>{});for(const id of s.players)recordGame(s.guildId,id,w.includes(id),w.includes(id)?10:0);}
async function runServer(c,s){
 if(s.id==='xo'||s.id==='hotxo')return xo(c,s,s.id==='hotxo');
 if(s.id==='rps')return rps(c,s);
 if(s.id==='dice')return dice(c,s);
 if(s.id==='chairs')return chairs(c,s);
 if(s.id==='mafia')return mafia(c,s);
 if(s.id==='hide')return hide(c,s);
 if(s.id==='replica')return textRace(c,s,'ريبلكا',['مغرب','مدينة','مدرسة','سيارة'],'حرف البداية');
 if(s.id==='country')return textRace(c,s,'خمّن الدولة',['المغرب','اليابان','فرنسا','البرازيل','مصر'],'اكتب اسم الدولة');
 if(s.id==='draw')return textRace(c,s,'خمّن الرسمة',['شمس','قطة','سيارة','بيت','كرة'],'خمّن الرسم');
 return textRace(c,s,'خمّن الكلمة',['مكتبة','برمجة','بطولة','مغامرة','حاسوب'],'خمّن الكلمة');
}
async function xo(c,s,hot){let p=shuffle(s.players),a=p[0],b=p[1],board=Array(9).fill('');let turn=0;const msg=await c.send({embeds:[xoEmbed(a,b,board,turn)],components:xoRows(board)});for(let n=0;n<25;n++){const m=await move(msg,turn?a:b,hot);if(m==null){await end(s,c,[turn?b:a]);return;}board[m]=turn?'⭕':'❌';if(won(board)){await msg.edit({embeds:[xoEmbed(a,b,board,turn)],components:xoRows(board,true)}).catch(()=>{});await end(s,c,[turn?b:a]);return;}if(!hot&&board.every(Boolean)){await end(s,c,[rnd([a,b])]);return;}if(hot){const used=board.filter(Boolean).length;if(used>5){const oldest=board.findIndex(x=>x);if(oldest>=0)board[oldest]='';}}turn^=1;await msg.edit({embeds:[xoEmbed(a,b,board,turn)],components:xoRows(board)}).catch(()=>{});}await end(s,c,[rnd([a,b])]);}
function xoRows(b,done=false){let rows=[];for(let r=0;r<3;r++)rows.push(new ActionRowBuilder().addComponents(...[0,1,2].map(k=>{let n=r*3+k;return new ButtonBuilder().setCustomId(`cell:${n}`).setLabel(b[n]||'·').setStyle(b[n]?ButtonStyle.Secondary:ButtonStyle.Primary).setDisabled(done||!!b[n]);})));return rows;}
const xoEmbed=(a,b,bx,t)=>new EmbedBuilder().setTitle('⭕ XO ❌').setDescription(`الدور: <@${t?b:a}>\n\n${bx.map((x,i)=>(x||'▫️')+((i+1)%3?' ':'\n')).join('')}`);
const won=b=>[[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]].some(([a,c,d])=>b[a]&&b[a]===b[c]&&b[a]===b[d]);
function move(msg,user,hot){return new Promise(res=>{const c=msg.createMessageComponentCollector({time:12000});c.on('collect',async x=>{if(x.user.id!==user)return x.reply({content:'ليس دورك.',ephemeral:true});await x.deferUpdate();c.stop('ok');res(Number(x.customId.split(':')[1]));});c.on('end',r=>{if(r!=='ok')res(null);});});}
async function rps(c,s){let alive=[...s.players];while(alive.length>1){const choices=new Map(),row=new ActionRowBuilder().addComponents(['حجرة','ورقة','مقص'].map((x,n)=>new ButtonBuilder().setCustomId(`r:${n}`).setLabel(x).setStyle(ButtonStyle.Primary)));const m=await c.send({content:'✊ **حجرة ورقة مقص** — اختر بسرعة!',components:[row]});const col=m.createMessageComponentCollector({time:10000});col.on('collect',async x=>{if(!alive.includes(x.user.id))return x.reply({content:'أنت لست ضمن الجولة.',ephemeral:true});choices.set(x.user.id,Number(x.customId.split(':')[1]));await x.reply({content:'تم تسجيل اختيارك.',ephemeral:true});});await new Promise(r=>col.on('end',r));const present=[...choices.values()];if(present.length<2){await end(s,c,[rnd(alive)]);return;}const has=[0,1,2].filter(n=>present.includes(n));let winSet=has.length===3||has.length!==2?has:[(has[0]+1)%3];alive=alive.filter(id=>winSet.includes(choices.get(id)));if(!alive.length)alive=[rnd(s.players)];if(alive.length>1)await c.send(`الجولة انتهت. المتبقون: ${alive.map(x=>`<@${x}>`).join('، ')}`);}await end(s,c,[alive[0]]);}
async function dice(c,s){const teams=[[],[]];shuffle(s.players).forEach((x,i)=>teams[i%2].push(x));let score=[0,0];for(let r=1;r<=3;r++){let a=1+Math.floor(Math.random()*6),b=1+Math.floor(Math.random()*6);score[0]+=a;score[1]+=b;await c.send(`🎲 الجولة ${r}: الفريق الأول **${a}** — الفريق الثاني **${b}**`);}await end(s,c,teams[score[0]>=score[1]?0:1]);}
async function chairs(c,s){let p=[...s.players];while(p.length>1){const seats=p.length-1,taken=new Set(),m=await c.send({content:`🪑 **الكراسي**\nهناك ${seats} مقاعد متاحة.`,components:[new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('chair').setLabel('اجلس').setStyle(ButtonStyle.Success))]});const col=m.createMessageComponentCollector({time:8000});col.on('collect',async x=>{if(!p.includes(x.user.id)||taken.has(x.user.id)||taken.size>=seats)return x.reply({content:'لا يمكنك الحجز الآن.',ephemeral:true});taken.add(x.user.id);await x.reply({content:'تم حجز مقعدك.',ephemeral:true});if(taken.size>=seats)col.stop();});await new Promise(r=>col.on('end',r));p=p.filter(x=>taken.has(x));if(!p.length)p=[rnd(s.players)];if(p.length>1)await c.send(`💥 خرج لاعب من الجولة. المتبقون: ${p.map(x=>`<@${x}>`).join('، ')}`);}await end(s,c,p);}
async function mafia(c,s){let p=shuffle(s.players), mafiaCount=Math.max(1,Math.floor(p.length/4)),mafia=new Set(p.slice(0,mafiaCount));for(const id of p){const m=await c.guild.members.fetch(id).catch(()=>null);m?.send(`🎭 دورك السري: **${mafia.has(id)?'مافيا':'مواطن'}**`).catch(()=>{});}await c.send('🌙 تبدأ ليلة المافيا. بعد 8 ثوانٍ تختار اللعبة ضحية عشوائية، ثم تعلن النتيجة.');await sleep(8000);const target=rnd(p.filter(x=>!mafia.has(x)));await c.send(`☀️ انتهت الليلة. خرج <@${target}>.`);const town=p.filter(x=>!mafia.has(x)&&x!==target),winner=mafia.size>=town.length?'مافيا':'مواطن';await end(s,c,p.filter(x=>winner==='مافيا'?mafia.has(x):!mafia.has(x)));}
async function hide(c,s){const seeker=s.players[0],rest=s.players.slice(1);await c.send(`🙈 **غميضة**\nالباحث: <@${seeker}>\nيختبئ الآخرون...`);await sleep(5000);const found=shuffle(rest).slice(0,Math.max(1,Math.floor(rest.length/2)));const winner=rnd(rest.filter(x=>!found.includes(x))||rest);await c.send(`🔎 وجد الباحث: ${found.length?mention(found):'لا أحد'}`);await end(s,c,[winner]);}
async function textRace(c,s,title,answers,instruction){const answer=rnd(answers);const m=await c.send(`🧠 **${title}**\n${instruction}\nابدأ الآن.`);const col=c.createMessageCollector({time:15000,filter:x=>s.players.includes(x.author.id)});let winner=null;col.on('collect',x=>{if(x.content.trim().toLowerCase()===answer.toLowerCase()){winner=x.author.id;col.stop();}});await new Promise(r=>col.on('end',r));await m.edit(`🧠 **${title}**\nالإجابة: **${answer}**\n${winner?`🏆 <@${winner}>`:'انتهى الوقت.'}`);await end(s,c,winner?[winner]:[]);}

async function mini(i,id){const data={button:['👆 **زر**','اضغط الزر!','CLICK'],fast:['⚡ **أسرع**','اكتب: **برق**','برق'],split:['✂️ **فكك**','أعد الكلمة: **مـكـتـبـة**','مكتبة'],merge:['🔗 **ادمج**','ادمج: **ب ر م ج ة**','برمجة'],flag:['🚩 **أعلام**','ما الدولة: 🇲🇦 ؟','المغرب'],reverse:['🔁 **اعكس**','اعكس: **Discord**','d||||ro||||csiD'.replaceAll('|','')],letter:['🔠 **حرف**','أكمل: مـدـرـسـ_','ة'],correct:['✏️ **صحح**','صحح: **مكتبه**','مكتبة'],sort:['🔢 **ترتيب**','رتب: **3 1 5 2 4**','1 2 3 4 5'],colors:['🎨 **ألوان**','اكتب: **أزرق**','أزرق'],emoji:['😀 **إيموجي**','أرسل: **🌹**','🌹'],reveal:['🃏 **اكشف**','الكلمة: **قـ _ ـب**','قلب']}[id];if(id==='button'){const row=new ActionRowBuilder().addComponents(new ButtonBuilder().setCustomId('mini:hit').setLabel('اضغط!').setStyle(ButtonStyle.Success));await i.reply({content:data[1],components:[row]});const m=await i.fetchReply();const col=m.createMessageComponentCollector({time:10000,max:1});const win=await new Promise(r=>{col.on('collect',async x=>{await x.reply({content:'🏆 فزت!',ephemeral:true});r(x.user.id);});col.on('end',()=>r(null));});if(win)recordGame(i.guildId,win,true,3);return;}await i.reply(data[1]);const ans=data[2];const col=i.channel.createMessageCollector({time:12000});let win=null;col.on('collect',m=>{if(m.author.bot)return;if(m.content.trim().toLowerCase()===ans.toLowerCase()){win=m.author.id;col.stop();}});await new Promise(r=>col.on('end',r));await i.channel.send(win?`🏆 <@${win}> فاز في **${names[id]||id}**!`:'⏱️ انتهى الوقت.');if(win)recordGame(i.guildId,win,true,3);}

export async function handleButton(i){const parts=i.customId.split(':');if(parts[0]==='lobby'){const s=activeGames.get(i.channelId);if(!s||s.id!==parts[1])return i.reply({content:'انتهى هذا اللوبي.',ephemeral:true});const a=parts[2];if(a==='join'){if(s.players.includes(i.user.id))return i.reply({content:'أنت منضم بالفعل.',ephemeral:true});if(s.players.length>=20)return i.reply({content:'اكتمل اللوبي.',ephemeral:true});s.players.push(i.user.id);return i.update({embeds:[embedLobby(s.id,s.players)],components:[lobbyRow(s.id)]});}if(a==='start'){if(s.players.length<2)return i.reply({content:'تحتاج اللعبة إلى لاعبين اثنين على الأقل.',ephemeral:true});s.started=true;clearTimeout(timers.get(i.channelId));return i.update({embeds:[embedLobby(s.id,s.players)],components:[lobbyRow(s.id)]}).then(()=>runServer(i.channel,s));}s.cancelled=true;activeGames.delete(i.channelId);clearTimeout(timers.get(i.channelId));return i.update({content:'تم إلغاء اللعبة.',embeds:[],components:[]});}if(parts[0]==='cell'||parts[0]==='r'||parts[0]==='chair'||parts[0]==='mini')return;}
export async function handleModal(){ }
